Added a configuration option --disable-noopt-retry that disables the compilation retries without optimization in the .c.o targets.

diff --git a/src/modules/static_module_makefile.in b/src/modules/static_module_makefile.in
--- a/src/modules/static_module_makefile.in
+++ b/src/modules/static_module_makefile.in
@@ -45,16 +45,25 @@ dummy:	Makefile linker_options modlist_headers modlist_segment module.pmod modul
 
 # GCC dumps core on some files @ OSF1
 # This kluge should work around that...
-# FIXME: Make this a configure option
 .c.o:
 	@echo "Compiling $<" ;\
 	rm -f $@.fail >/dev/null 2>&1; \
-	if $(CC) $(CFLAGS) -c $< -o $@ ; then : ;\
-	else \
-	  echo "WARNING: Compiler failure! Trying without optimization!" >&2;\
-	  echo "$(CC) $(NOOPT_CFLAGS) -c $< -o $@" >&2;\
-	  echo "$(CC) $(CFLAGS) -c $< -o $@" >$@.fail ;\
-	  NO_ULIMIT=yes $(CC) $(NOOPT_CFLAGS) -c $< -o $@ ;\
+	if $(CC) $(CFLAGS) -c $< -o $@ ; then : ; else \
+	  status=$$?; \
+	  if test x"@noopt_retry@" = xyes ; then \
+	    echo "WARNING: Compiler failure! Trying without optimization!" >&2;\
+	    echo "$(CC) $(PREFLAGS) $(CFLAGS) -c $< -o $@" >$@.fail ;\
+	    if NO_ULIMIT=yes $(CC) $(PREFLAGS) $(NOOPTFLAGS) -c $< -o $@ ; then : ; else \
+	      status=$$?; \
+	      echo "Compilation command was:" >&2;\
+	      echo "$(CC) $(PREFLAGS) $(NOOPTFLAGS) -c $< -o $@" >&2 ;\
+	      exit $$status; \
+	    fi; \
+	  else \
+	    echo "Compilation command was:" >&2;\
+	    echo "$(CC) $(PREFLAGS) $(CFLAGS) -c $< -o $@" >&2 ;\
+	    exit $$status; \
+	  fi; \
 	fi
 
 linker_options: Makefile $(MODULE_ARCHIVES)
