Reverting a change that got in by mistake in revision 1.238.

diff --git a/src/Makefile.in b/src/Makefile.in
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -307,8 +307,20 @@ hilfe: $(TMP_BINDIR)/hilfe Makefile
 .c.o:
 	@echo "Compiling $<" ;\
 	if $(CC) $(CFLAGS) -c $< -o $@ ; then : ; else \
-	  echo "Compilation command was:" >&2;\
-	  echo "$(CC) $(CFLAGS) -c $< -o $@" >&2 ;\
+	  echo "WARNING: Compiler failure! Trying without optimization!" >&2;\
+	  echo "echo $(CC) $(PREFLAGS) $(NOOPTFLAGS) -c $< -o $@" >&2 ;\
+	  NO_ULIMIT=yes; \
+	  export NO_ULIMIT; \
+	  if $(CC) $(PREFLAGS) $(NOOPTFLAGS) -c $< -o $@ ; then : ; else \
+	    err=$$?; \
+	    if test "x$(FALLBACK_CC)" = "x"; then \
+	      exit $$err; \
+	    else \
+	      echo "WARNING: Compiler failure! Trying fallback compiler!" >&2;\
+	      echo "echo $(FALLBACK_CC) $(PREFLAGS) $(NOOPTFLAGS) -c $< -o $@" >&2 ;\
+	      $(FALLBACK_CC) $(PREFLAGS) $(NOOPTFLAGS) -c $< -o $@ ;\
+	    fi; \
+	  fi; \
 	fi
 
 #
