autodoc -> refdoc

diff --git a/src/Makefile.in b/src/Makefile.in
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -187,12 +187,12 @@ all: module_objects hilfe
 	$(MAKE) $(MAKE_FLAGS) $(MAKE_PARALLEL) pike
 
 documentation: just-tinstall
-	@if [ -f "$(SRCDIR)/../autodoc/Makefile" ]; then \
+	@if [ -f "$(SRCDIR)/../refdoc/Makefile" ]; then \
 	  PIKE="`pwd`/test-pike"; \
 	  export PIKE; \
-	  (cd $(SRCDIR)/../autodoc && $(MAKE) PIKE="$$PIKE") || exit 1; \
+	  (cd $(SRCDIR)/../refdoc && $(MAKE) PIKE="$$PIKE") || exit 1; \
 	else \
-	  echo "Autodoc directory not found."; \
+	  echo "Refdoc directory not found."; \
 	  exit 1; \
 	fi
 
